// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFDyaowf8ZQvvZVM6UwV2z4oUVcfrX5cU',
    appId: '1:34848410598:web:4499486b8c8b62c5fd2427',
    messagingSenderId: '34848410598',
    projectId: 'image-location-tracking-8801e',
    authDomain: 'image-location-tracking-8801e.firebaseapp.com',
    storageBucket: 'image-location-tracking-8801e.appspot.com',
    measurementId: 'G-H8TD31BRJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeeI6rKtxs61iJUq_1njI0tGtSp2CB2qk',
    appId: '1:34848410598:android:7ef112271cca30f3fd2427',
    messagingSenderId: '34848410598',
    projectId: 'image-location-tracking-8801e',
    storageBucket: 'image-location-tracking-8801e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfoJ3U9NhWTXFL0CV_0hoN9OFcIYVN5YQ',
    appId: '1:34848410598:ios:3383562bc87b96effd2427',
    messagingSenderId: '34848410598',
    projectId: 'image-location-tracking-8801e',
    storageBucket: 'image-location-tracking-8801e.appspot.com',
    iosBundleId: 'com.example.imageLocationTracking',
  );
}
